version: '3.8'

services:
  db:
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ze_partners
      POSTGRES_USER: zeuser
      POSTGRES_PASSWORD: zepassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
